server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/IdeaProjects/2024/bank-system/config/{application}
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

#  security:
#    user:
#      name: admin
#      password: admin
#      roles:
#        - CONFIG